---
title: "Long term station data analysis"
author: "Brian Yurk"
date: "12/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
```

Also had a weird problem here. This time it was on April 8.

```{r}
#ht <- 24.4 #station height in meters

col_names <- c("Date","Time","Temp","RH","Dewpt","WS","WD","Gust","LoCloudHt","MedCloudHt","HiCloudHt","Vis","AtmPres","SLP","Altim","Precip","WindChill","HeatIndex","empty")

col_types <- cols("D","t","d","d","d","d","d","d","d","d","d","d","d","d","d","d","d","d","d")

d1 <- read_csv('./MKE/MKE_19480101_19591231.csv',skip=9+2376,col_names=col_names,col_types=col_types,na=c("","m","M","NC"),n_max=107574-2376) %>% select(-empty)

d2 <- read_csv('./MKE/MKE_19600101_19891231.csv',skip=9,col_names=col_names,col_types=col_types,na=c("","m","M","NC"),n_max=233776) %>% select(-empty)

d3 <- read_csv('./MKE/MKE_19900101_20201207.csv',skip=9,col_names=col_names,col_types=col_types,na=c("","m","M","NC"),n_max=270397) %>% select(-empty)

data <- bind_rows(d1,d2,d3)
col_units <- c("Date","EST","F","perc","F","mph","deg","ft","ft","ft","mi","hPa","hPa","hPa","in","F","F")

#drop two problematic rows (time change?)
#prob_rows <- which(is.na(data$Time))
#data <- data[-prob_rows,]

data <- data %>% mutate(datetime=ymd(Date,tz="EST")+hms(Time))
```



```{r}
#let's look at the lengths of runs of NA values in the wind speeds
rle_ws <- rle(is.na(data$WS))
rl_ws <- rle_ws$lengths[rle_ws$values]
rl_ws
print(table(rl_ws))
```

```{r}
dp_from_ws <- function(ws,ht=10){ #assumes ws units are miles per hour
  ws10 <- ws*log(200)/log(20*ht) #estimate speed at 10m
  ws10kt <- ws*0.868976 #mph to knots
  q <- ws10kt^2*(ws10kt-12) #threshold 12 knots as in Fryberger and Dean
  q <- q*(q>0) #dp should be zero if ws is below threshold
}
data <- data %>% mutate(dp = dp_from_ws(WS))
saveRDS(data,file="./MKE/MKE_19471231_20201207_dp.rds")
```

